# Generated by Django 6.0.2 on 2026-03-03 20:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdata',
            name='vein_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='vein_embedding_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='biometric_type',
            field=models.CharField(choices=[('FACE', 'Face'), ('VEIN', 'Vein')], max_length=10),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='face_template',
            field=models.ImageField(blank=True, null=True, upload_to='face_templates'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
