# Generated by Django 6.0.2 on 2026-03-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_biometricdata_vein_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricdata',
            name='vein_embedding',
        ),
    ]
