# Generated by Django 6.0.2 on 2026-03-03 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_biometricdata_vein_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdata',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
